# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 80cdd8e2c71c0ead346752ecbb5cfdd6c9b2a709ed91b71a046ec70fcc1735c005a416e2dd2f4a16865bdbaaeb7e394a3995041239e7befdd7f39fd541a24d89

test:
  secret_key_base: 7d2b12e9f3801038da3dda51f378b65f48eca137e76e65f46681859308cefd51f066c923bc9edfb4dbfbc0e42e81d3c6bcfd587f68eb18cdccfaed9fcfed9dd1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
